### ISSUE TITLE
Enhancement - report HTTP status code

### ISSUE THREAD

**Issue by hsiboy** [sandalon/sitemap-validator#1]
Hi Corey, great little tool you got here, and i've used it to parse and check a multi-part sitemap containing in excess of 2,000,000 urls.

However, it just prints `Bad URL: <URL>` because the current stanza is this:

```
if(resp.statusCode != task.code) {
      console.log('Bad URL: ' + task.url);
      callback();
      return;
    }
```

If it was modified to:

```
if(resp.statusCode != task.code) {
      console.log(resp.statusCode + "," + task.url);
      callback();
      return;
    }
```
You could see why the URL was "bad" - i.e not a 200 or whatever was passed in with the `-c` option.

I've made this modification locally, and discovered that a change made in the caching tier responded with 301 for a lot of URLs that were published in the sitemap, and googlebot doesn't like 301s much.

Also, if piping the output from STDERR to a log, you get CSV. Which, with 2,000,000 urls, you need ;-)

**Comment by sandalon** [comment]
Hi Stuart, I'm glad you found it useful.  I agree that having the response code in the output would be quite helpful.  I've gone ahead and made the change as you suggested.
